
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: eddiev
  password:

development:
  <<: *default
  database: lim_api_development

test:
  <<: *default
  database: lim_api_test

production:
  <<: *default
  database: lim_api_production
  username: lim_api
  password: <%= ENV['LIM_API_DATABASE_PASSWORD'] %>
